// tag::DE[]
=== Auswirkungen von DDD auf das Unternehmen

Themeneinreicher: Hermann Wook (hwoock) 

Status: EINGEREICHT

==== Kurzbeschreibung
Software Projekte werden mit der Zeit in der Regel zäher, zerbrechlicher, fehleranfälliger, … Der Grund liegt oft in zu vielen Abhängigkeiten, schlechter Kohäsion und hoher Kopplung. DDD bietet dort Abhilfe und ist auch meist ein guter Einstieg für die immer beliebter werdenden µServices. DDD ist aber mehr als nur das Schneiden von Komponenten. Vieles davon wird sehr oft übersehen. DDD erfordert außerdem ein oft unterschätztes Maß an Agilität.

==== Welche Herausforderung verbindet sich mit dem Thema?
DDD beinhaltet Themen wie: Deep Insight, Break Through, Supple Design, Large Structures, … Diese werden oft übersehen. Dadurch verliert DDD viel von seiner Stärke.

Außerdem ist DDD ein sehr agiler Ansatz, der bei richtiger Umsetzung starken Einfluss auf Arbeitsabläufe und Firmenstrukturen hat. Dadurch kann DDD scheitern.

==== Wo tritt das Problem im Markt auf, und wer hat ein Interesse an der Lösung des Problems?
Das Problem tritt überall dort auf, wo DDD zum Einsatz kommt und die entsprechende Erfahrung in dessen Umsetzung fehlt.

Von Nutzen ist das Thema für: Firma, Manager, SW-Entwicklung, Anwender

==== Welchen Beitrag leistet die Bearbeitung des Themas? Was wird besser, wenn dieses Thema bearbeitet wurde?
Durch die Bearbeitung des Themas soll gezeigt werden, was mit DDD erreicht werden kann. Welche Probleme gelöst werden. Ebenso sollen aber auch die Auswirkungen aufs Unternehmen gezeigt werden, oder warum DDD scheitern kann. Welche Voraussetzungen müssen gegeben sein, damit DDD seinen Nutzen bringt?

==== Optionale Angaben zu Links, Literatur, Verweisen aller Art
Eric Evans +
https://www.amazon.de/Domain-Driven-Design-Tackling-Complexity-Software/dp/0321125215/ref=sr_1_1?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=XDYQ8RIVKH7L&keywords=eric+evans&qid=1641208354&s=books&sprefix=eric+evans%2Cstripbooks%2C107&sr=1-1

Vaughn Vernon +
https://www.amazon.de/Implementing-Domain-Driven-Design-Vaughn-Vernon/dp/0321834577/ref=pd_sbs_1/261-1226243-1174710?pd_rd_w=k2WD6&pf_rd_p=b1c388c3-48c2-4960-8532-fa8f1477aee9&pf_rd_r=8BJYEYJJ2HFE3RRBSVB4&pd_rd_r=118b996b-1eae-4186-90c4-e950aa7585b2&pd_rd_wg=tZg9Q&pd_rd_i=0321834577&psc=1

==== Sind Sie generell daran interessiert, an einer Themengruppe für Ihr eingereichtes Thema mitzuwirken?

==== Empfohlene Größe der Thema-Arbeitsgruppe
5-10 Personen
