// tag::DE[]
=== Einsatz unterschiedlicher NoSQL Datenbanken im Projekt
Themeneinreicher: Hermann Woock

Status: Freigegeben

==== Hintergrund
NoSQL-Datenbanken sind längst kein Novum mehr. In vielen Projekten sind sie Standard, in vielen aber auch nicht. 

Wer bislang nur mit relationalen Datenbanken zu tun hatte, kann sich oft nicht vorstellen, wie der Einsatz von NoSQL-Datenbanken gelingen kann:
- Welche Möglichkeiten stecken in solchen Datenbanken und was bringen sie für einen Gewinn?
- Welche Typen von NoSQL Datenbanken gibt es und wofür können sie eingesetzt werden?
- Gibt es Gefahren, auf die man achten sollte?

Das Thema ist interessant für Architekten, Entwicklung, Betrieb, DB-Administratoren

==== Aufgabenstellung
Es sollen diese Fragen beantwortet werden:
- Welche Probleme lassen sich mit NoSQL-Datenbanken lösen und welche neuen Probleme bekomme ich?
- Wie kann man den besten Nutzen aus NoSQL-Datenbanken ziehen?
- Welche Fähigkeiten und Wissen sind erforderlich?
- Wie müssen NoSQL-Datenbanken in die Architektur berücksichtigt werden?

Weitere Themen in diesem Zusammenhang sind Event Sourcing, Eventually Consistency, Skalierbarkeit, Ausfallsicherheit, Lizenzen oder BASE

Ein paar gelungene Beispiele aus der Praxis mit Tipps und Tricks würden weiterhelfen.

==== Referenzen
Fowler, M., & Sadalage, P. J. (2012). NoSQL distilled.  Pearson Education. 

==== Gruppengröße
Das Thema soll von einer Gruppe mit 5-7 Personen bearbeitet werden.
