// tag::DE[]
=== Erfahrungen mit Event-Driven Architekturen
Themeneinreicher: Hermann Woock

Status: Freigegeben

===== Hintergrund

Nicht erst seit der Veröffentlichung von Vernons Buch „Implementing Domain-Driven Design“ mit dem Vorwort von Eric Evans sind Event-Driven Architekturen von Interesse. Event-Driven Architekturen (EDA) bieten ein hohes Maß an Flexibilität in der Software. Sei es im Programmablauf oder in der Datenerfassung. EDAs werden in vielen Orten bereits erfolgreich eingesetzt. Auch Cloud Provider bieten Lösungen an. Immer mehr Frameworks kommen hierzu auf den Markt. Monitoring, BI und viele weitere Bereiche machen von EDAs Gebrauch.

Event-Driven Architekturen helfen dabei, flexible Systeme zu schaffen, die sich an Veränderungen anpassen und Entscheidungen in Echtzeit treffen können. Ereignisse werden erfasst, sobald sie von Ereignisquellen wie Internet-of-Things-Geräten (IoT), Anwendungen und Netzwerken eintreten, sodass Event-Produzenten und Event-Consumer Status- und Reaktionsinformationen in Echtzeit austauschen können. In diesem Kontext wird auch häufig über die Konzepte des Event Sourcings und CQRS gesprochen, die weitere Herausforderungen bieten, aber auch spannende Vorteile versprechen.

===== Aufgabenstellung

Diese Fragen sollen behandelt werden:

* Für welche Einsatzzwecke eignet sich dieser Architekturstil?
* Welche Muster und Technologien können eingesetzt werden?
* Wie ordnen sich folgende Punkte in das Thema ein: CQRS, Event Sourcing, SAGA, Messaging, Reactive Programming, Kafka?
* Wie löst man folgende Probleme?
** Überholung
** Idempotenz
** Versionierung
** Inhalte von Events

===== Referenzen

Vernon, V. (2013). Implementing Domain-Driven Design. Pearson ITP. 

Domogalla, M. (2022, April 21). Software-Architektur.tv: Softwarearchitektur MIT events, event sourcing UND CQRS. Developer. https://www.heise.de/news/software-architektur-tv-Softwarearchitektur-mit-Events-Event-Sourcing-und-CQRS-7061126.html 

===== Gruppengröße

Das Thema soll von einer Gruppe mit 3 bis 7 Personen bearbeitet werden.