// tag::DE[]
=== Frontend-Entwicklung in großen Projekten
Themeneinreicher: Johannes Hochrainer

Status: Freigegeben

===== Hintergrund

Große Softwaresysteme werden in der Regel von mehreren Entwicklungsteams umgesetzt. Während sich im Backend Feature-Teams durchgesetzt haben, wird in vielen Projekten das Frontend von einem einzigen Team entwickelt. Doch auch im Frontend setzt sich immer mehr der Microservice-Gedanke durch: Unabhängige Teams arbeiten an einem fachlichen Frontend-Baustein und können ihren Baustein unabhängig von den anderen Teams entwickeln und ausliefern. Für die Umsetzung dieser sogenannten Microfrontend-Architektur gibt es verschiedenste methodische und technische Ansätze.

===== Aufgabenstellung

Folgende Fragen sollen beantwortet werden:

* Wie kann ein Frontend flexibel und effizient mit verschiedenen Entwicklungsteams umgesetzt werden? Dazu gehören u. a. Folgende:
** Micro Frontends
** Self-Contained Systems
** Backends for Frontends Pattern
** Organisationsinterne Komponentenbibliotheken (ähnlich Angular Material)
** Webpack Module Federation
** Monorepos (z. B. mit Nx)
* Wie baut man ein bestehendes monolithisches Frontend zu einem sauber modularisierten, parallel entwickelbaren Frontend um?

===== Referenzen

- Micro Frontends, https://micro-frontends.org/
- Self Contained Systems, https://scs-architecture.org/
- Backends for Frontends Pattern - Cloud Design Patterns, https://docs.microsoft.com/en-us/azure/architecture/patterns/backends-for-frontends
- Angular Material, https://material.angular.io/
- Nx Monorepo, https://nx.dev/
- Webpack Module Federation, https://webpack.js.org/concepts/module-federation/

==== Gruppengröße

Das Thema soll von einer Gruppe mit 5 bis 7 Personen bearbeitet werden.