// tag::DE[]
=== Maschinelles Lernen in der Praxis
Themeneinreicher: Hermann Woock

Status: Freigegeben

==== Hintergrund
Maschinelles Lernen (ML) entwickelt sich immer mehr von einer Fiktion zu einer nicht mehr wegzudenkender Technik. Wer sich nicht früh mit ML beschäftigt, für den kann der Zug später vielleicht schon abgefahren sein. Dennoch ist ein Investment sehr riskant.

Einsatzgebiete sind sehr vielfältig: Baubranche, Automobilindustrie, Finanzwesen, Behörden, Logistik, Marketing. Die Umsetzung erfordert allerdings neue Talente, und wirft Fragen auf. Niemand sollte diese Entwicklung verschlafen.

Im Rahmen der Digitalisierung oder der stärker werdenden Konkurrenz braucht es neue Lösungen, bei denen ML eine gute Hilfe anbieten kann. Im Bereich von Business Intelligence oder Big Data braucht es neue Verfahren, bei denen ML unterstützen kann.

=== Aufgabenstellung
Der Beitrag soll Mut machen, einen Einstieg in dieses Thema zu finden.

Es gibt viele Dinge zu klären:

- Welche Probleme lassen sich mit ML lösen?
- Welcher Aufwand steckt dahinter?
- Welche Fähigkeiten und Wissen sind bei der Umsetzung erforderlich?
- Welche rechtlichen Einflüsse müssen beachtet werden?
- Was sind die Erfolgsfaktoren?

==== Referenzen

==== Gruppengröße
Das Thema soll von einer Gruppe mit 5-7 Personen bearbeiten werden.