// tag::DE[]
=== Sind SOLID-Prinzipien noch zeitgemäß?
Themeneinreicher: Johannes Hochrainer

Status: Freigegeben

==== Hintergrund

In den letzten Jahren gab es vermehrt Stimmen, die behaupteten, dass die SOLID-Prinzipien nicht mehr zeitgemäß wären. So sorgte etwa 2021 Dan North für Aufregung, als er behauptete, jedes einzelne SOLID-Prinzip wäre falsch. Nach etwas Zeit legte er nach und schlug als Alternative seine sogenannten „CUPID-Properties“ vor:

- Composable
- Unix Philosophy
- Predictable
- Idiomatic
- Domain-based

==== Aufgabenstellung

Die Themenarbeitsgruppe soll folgende Fragen klären:

- Welche Kritikpunkte gibt es an SOLID und können sie wissenschaftlich bestätigt werden?
- Erfüllt CUPID alle Anforderungen, um als Orientierung bei der Software-Entwicklung zu dienen?
- Gibt es Gemeinsamkeiten zwischen SOLID und CUPID?
- Gibt es Einsatzgebiete, die sich besonders für SOLID oder für CUPID eignen?
- Gibt es auch andere Sammlungen von Prinzipien, an denen sich Entwickler orientieren können?

==== Referenzen

- Principles Of Object Oriented Design, http://wiki.c2.com/?PrinciplesOfObjectOrientedDesign
- CUPID—the back story, https://dannorth.net/2021/03/16/cupid-the-back-story/
- CUPID—for joyful coding, https://dannorth.net/2022/02/10/cupid-for-joyful-coding/

==== Gruppengröße

Das Thema soll von einer Gruppe mit 3-5 Personen bearbeiten werden.
