= https://isaqb.org[iSAQB] Topic Backlog for CPSA®-Expert Level

:toc:
:toc-placement!:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Status
image:https://github.com/isaqb-org/topic-backlog-expert-level/workflows/CI%20-%20Releases%20and%20Main/badge.svg?branch=main["CI – Releases and Main"]
image:https://img.shields.io/github/last-commit/isaqb-org/topic-backlog-expert-level/main.svg["Last commit"]
image:https://img.shields.io/github/contributors/isaqb-org/topic-backlog-expert-level.svg["Contributors",link="https://github.com/isaqb-org/topic-backlog-expert-level/graphs/contributors"]
image:https://img.shields.io/github/issues/isaqb-org/topic-backlog-expert-level.svg["Issues",link="https://github.com/isaqb-org/topic-backlog-expert-level/issues"]
image:https://img.shields.io/github/issues-closed/isaqb-org/topic-backlog-expert-level.svg["Issues closed",link="https://github.com/isaqb-org/topic-backlog-expert-level/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+"]


This is <<copyrighted,copyrighted work>>.

== Content
This repository contains a list of topics that can be chosen for the iSAQB® CPSA®-Expert Level examination.

toc::[]

== How to contribute or participate
Create an issue, a merge- or pull-request

== How to build this project
Clone the repository—including the submodules:

--
[source,shell]
----
Via SSH:
git clone git@github.com:isaqb-org/topic-backlog-expert-level.git --recursive

Via HTTPS:
git clone https://github.com/isaqb-org/topic-backlog-expert-level.git --recursive
----
--

. Build the project with http://www.gradle.com[gradle] (you need a locally installed JDK 17 or higher) via `./gradlew buildDocs`.
. Once the "BUILD SUCCESSFUL" is show, you can review the build result under `./build/index.html`

== Additional translations/languages
include::docs-ext/EXTERNAL_DOCUMENTS_README.adoc[]

== Maintainers

This repository is currently maintained by the Expert Level Maintainer group of iSAQB>
It was forked from https://github.com/isaqb-org/advanced-template,
so the contributors of that project basically contributed to this one, too.


[[copyrighted]]
== Licensing and Copyright

include::license-copyright/LICENSE.adoc[]
